project:
  type: website
  render:
    - "*.qmd"
    - "notes/*.qmd"
  output-dir: docs

website:
  title: "PSYCH 490 • Fall 2023"
  comments: 
    hypothesis:
      theme: clean
  navbar:
    left:
      - href: index.qmd
        text: home
      - href: about.qmd
        text: about
      - href: schedule.qmd
        text: schedule
      - href: evaluation.qmd
        text: evaluation
      - href: deadlines.qmd
        text: deadlines
      - href: policies.qmd
        text: policies
      - text: notes
        menu:
          - href: "notes/wk01-2023-08-21.qmd"
          - href: "notes/wk01-2023-08-23.qmd"
          - href: "notes/wk01-2023-08-25.qmd"
          - href: "notes/wk02-2023-08-28.qmd"
          - href: "notes/wk02-2023-08-30.qmd"
          - href: "notes/wk02-2023-09-01.qmd"
          - href: "notes/wk03-2023-09-06.qmd"
          - href: "notes/wk03-2023-09-08.qmd"
          - href: "notes/wk04-2023-09-11.qmd"
          - href: "notes/wk04-2023-09-13.qmd"
          - href: "notes/wk04-2023-09-15.qmd"
      - text: exercises
        menu: 
          - href: "ex01-read-a-scientific-paper.qmd"
          - href: "ex02-norms-counternorms.qmd"
          - href: "ex03-scientific-integrity.qmd"
          - href: "ex04-p-hacking.qmd"
          - href: "ex05-apes.qmd"
          - href: "ex06-replication.qmd"
          - href: "ex07-sharing.qmd"
          - href: "final-project.qmd"
      - text: surveys
        menu: 
          - href: "survey-01.qmd"
          - href: "survey-02.qmd"
format:
  html:
    theme: cosmo
    css: include/css/styles.css
    toc: true
    number-sections: false
    citations-hover: true
    footnotes-hover: true
    bibliography: [include/bib/packages.bib, include/bib/psu-repro.bib]
    csl: include/bib/apa.csl

editor: source
    