---
title: "Exercise 03"
subtitle: "Violations of scientific integrity"
---

## Dates {-}

Due: [Thursday, March 30, 2023]{.orange_due}.

## Goals {-}

The integrity of individual scientists and teams of scientists can lend credence to or undermine scientific methods and findings.
In this exercise, we will explore some of the mechanisms by which violations of scientific integrity come to light.

## Assignment {-}

Choose a case study relating to a violation of scientific integrity as reported to the U.S. National Institutes of Health (NIH) Office of Research Integrity ([ORI](https://ori.hhs.gov/)).

Choose a second report about a violation of scientific integrity from [Retraction Watch](https://retractionwatch.com/).

Compare and contrast the two cases you have chosen, focusing on answering the following questions:

1. What specific violation was alleged?
2. Why are the alleged behavior(s) considered a violation of scientific integrity?
3. What are/were the consequences to the people involved?
4. What could be done to reduce the likelihood that similar alleged violations of scientific integrity occur in the future?

## Submit {-}

In a short (2-3 pp double-spaced report) discuss your answers to these questions and how the two cases are similar or differ.
