---
title: "Exercise 03"
subtitle: "Alleged violations of scientific integrity"
---

## Dates {-}

Due: [Friday, September 29]{.orange_due}.

## Goals {-}

The integrity of individual scientists and teams of scientists can lend credence to or undermine scientific methods and findings.
In this exercise, we will explore some of the mechanisms by which violations of scientific integrity come to light.

## Assignment {-}

Choose two cases where violations of scientific integrity have been alleged.
Your cases must come from two different sources from among the following:

- A case study relating to a violation of scientific integrity as reported to the U.S. National Institutes of Health (NIH) Office of Research Integrity ([ORI](https://ori.hhs.gov/).
- A report about a violation of scientific integrity from the [Retraction Watch](https://retractionwatch.com/) database.
- A post or posts on the [Data Colada site](http://datacolada.org).
- A report in a newspaper or scientific journal.

Compare and contrast the two cases you have chosen, focusing on answering the following questions:

1. What specific violation or violations were alleged?
2. Why are the alleged behavior(s) considered a violation of scientific integrity?
3. What are/were the consequences to the people involved?
4. What could be done to reduce the likelihood that similar alleged violations of scientific integrity occur in the future?

## Submit {-}

In a short (2-3 pp double-spaced report) discuss your answers to these questions and how the two cases are similar or differ from one another.

Please use the APA format for your paper.
Remember the following template document is a good place to start:

<https://docs.google.com/document/d/1IIKwtH7eVXIkQMz4FwMuKol6hMDT3ra9/copy>
