---
title: "2023-10-06 Fri"
subtitle: "Work session: P-hacking"
author: "Rick Gilmore"
format: revealjs
bibliography: [../include/bib/packages.bib, ../include/bib/psu-repro.bib]
csl: ../include/bib/apa.csl
css: ../include/css/styles.css
footer: "[PSYCH 490.009](../index.html): 2023-10-06 Friday"
---

# Overview

## Announcements

- [Due]{.orange_due}
    - [Exercise 04: P-hack your way to scientific glory](exercises/ex04-p-hacking.qmd) write-up.

## Today

*Work session: P-hacking*

- Discuss [Exercise 04: P-hack your way to scientific glory](exercises/ex04-p-hacking.qmd).
- Work session
    - [Final project proposals](exercises/final-project.qmd), [due Friday, October 13]{.orange_due}.

## Discuss p-hacking exercise {-}

1. Who got a "significant" result?
1. How many different analyses did you try?
1. Who changed their analysis after finding a significant result?
1. Did anyone try another analysis--after you got a significant result--and *keep* the non-significant result?

## Enter (anonymized) data into spreadsheet

- Use in an exercise on Monday
- Sheet: <https://docs.google.com/spreadsheets/d/1fnSwFrUcKvgqq_agDLe4t2DHXHtHoOlmLdtLVRSemrI/edit?usp=sharing>

- Choose a student_id (integer) for yourself

# Next time

*Bias*

- Read
    - [@Ritchie2020-fm], Chapter 4
- [Class notes](wk08-2023-10-09.qmd)

# Resources

## References