project:
  type: website
  render:
    - "*.qmd"
    - "notes/*.qmd"
    - "exercises/*.qmd"
    - "surveys/*.qmd"
  output-dir: "../docs"

website:
  title: "PSYCH 490 • Fall 2023"
  comments: 
    hypothesis:
      theme: clean
  navbar:
    left:
      - href: index.qmd
        text: home
      - href: about.qmd
        text: about
      - href: schedule.qmd
        text: schedule
      - href: evaluation.qmd
        text: evaluation
      - href: deadlines.qmd
        text: deadlines
      - href: policies.qmd
        text: policies
      - text: exercises
        menu: 
          - href: "exercises/ex01-read-a-scientific-paper.qmd"
          - href: "exercises/ex02-norms-counternorms.qmd"
          - href: "exercises/ex03-scientific-integrity.qmd"
          - href: "exercises/ex04-p-hacking.qmd"
          - href: "exercises/ex05-apes.qmd"
          - href: "exercises/ex06-replication.qmd"
          - href: "exercises/ex07-sharing.qmd"
          - href: "exercises/final-project.qmd"
      - text: supplemental
        menu: 
          - href: "surveys/survey-01.qmd"
          - href: "surveys/survey-02.qmd"
          - href: "surveys/retraction-watch.qmd"
          - href: "surveys/simmons-etal-2011-suppl.qmd"
          - href: "surveys/p-hacking-suppl.qmd"
          - href: "surveys/plotting-degrees-of-freedom.qmd"
          - href: "surveys/many-viz.qmd"
format:
  html:
    theme: cosmo
    css: include/css/styles.css
    toc: true
    number-sections: false
    citations-hover: true
    footnotes-hover: true
    bibliography: [include/bib/packages.bib, include/bib/psu-repro.bib]
    csl: include/bib/apa.csl

editor: source
    