project:
  type: website
  render:
    - "*.qmd"
    - "notes/*.qmd"
    - "exercises/*.qmd"
    - "surveys/*.qmd"
  output-dir: "../docs"

website:
  title: "PSYCH 490 • Fall 2023"
  comments: 
    hypothesis:
      theme: clean
  navbar:
    left:
      - href: index.qmd
        text: home
      - href: about.qmd
        text: about
      - href: schedule.qmd
        text: schedule
      - href: evaluation.qmd
        text: evaluation
      - href: deadlines.qmd
        text: deadlines
      - href: policies.qmd
        text: policies
      - text: "notes wk01-wk07"
        menu:
          - href: "notes/wk01-2023-08-21.qmd"
          - href: "notes/wk01-2023-08-23.qmd"
          - href: "notes/wk01-2023-08-25.qmd"
          - text: "--Week 02--"
          - href: "notes/wk02-2023-08-28.qmd"
          - href: "notes/wk02-2023-08-30.qmd"
          - href: "notes/wk02-2023-09-01.qmd"
          - text: "--Week 03--"
          - href: "notes/wk03-2023-09-06.qmd"
          - href: "notes/wk03-2023-09-08.qmd"
          - text: "--Week 04--"
          - href: "notes/wk04-2023-09-11.qmd"
          - href: "notes/wk04-2023-09-13.qmd"
          - href: "notes/wk04-2023-09-15.qmd"
          - text: "--Week 05--"
          - href: "notes/wk05-2023-09-18.qmd"
          - href: "notes/wk05-2023-09-20.qmd"
          - href: "notes/wk05-2023-09-22.qmd"
          - text: "--Week 06--"
          - href: "notes/wk06-2023-09-27.qmd"
          - href: "notes/wk06-2023-09-29.qmd"
          - text: "--Week 07--"
          - href: "notes/wk07-2023-10-02.qmd"
          - href: "notes/wk07-2023-10-04.qmd"
          - href: "notes/wk07-2023-10-06.qmd"
      - text: "notes wk08-wk016"
        menu:
          - text: "--Week 08--"
          - href: "notes/wk08-2023-10-09.qmd"
          - href: "notes/wk08-2023-10-11.qmd"
          - href: "notes/wk08-2023-10-13.qmd"
          - text: "--Week 09--"
          - href: "notes/wk09-2023-10-16.qmd"
          - href: "notes/wk09-2023-10-18.qmd"
          - href: "notes/wk09-2023-10-20.qmd"
          - text: "--Week 10--"
          - href: "notes/wk10-2023-10-23.qmd"
          - href: "notes/wk10-2023-10-25.qmd"
          - href: "notes/wk10-2023-10-27.qmd"
          - text: "--Week 11--"
          - href: "notes/wk11-2023-10-30.qmd"
          - href: "notes/wk11-2023-11-01.qmd"
          - href: "notes/wk11-2023-11-03.qmd"
          - text: "--Week 12--"
          - href: "notes/wk12-2023-11-06.qmd"
          - href: "notes/wk12-2023-11-08.qmd"
          - href: "notes/wk12-2023-11-10.qmd"
          - text: "--Week 13--"
          - href: "notes/wk13-2023-11-13.qmd"
          - href: "notes/wk13-2023-11-15.qmd"
          - href: "notes/wk13-2023-11-17.qmd"
      - text: exercises
        menu: 
          - href: "exercises/ex01-read-a-scientific-paper.qmd"
          - href: "exercises/ex02-norms-counternorms.qmd"
          - href: "exercises/ex03-scientific-integrity.qmd"
          - href: "exercises/ex04-p-hacking.qmd"
          - href: "exercises/ex05-apes.qmd"
          - href: "exercises/ex06-replication.qmd"
          - href: "exercises/ex07-sharing.qmd"
          - href: "exercises/final-project.qmd"
      - text: supplemental
        menu: 
          - href: "surveys/survey-01.qmd"
          - href: "surveys/survey-02.qmd"
          - href: "surveys/retraction-watch.qmd"
          - href: "surveys/simmons-etal-2011-suppl.qmd"
          - href: "surveys/p-hacking-suppl.qmd"
format:
  html:
    theme: cosmo
    css: include/css/styles.css
    toc: true
    number-sections: false
    citations-hover: true
    footnotes-hover: true
    bibliography: [include/bib/packages.bib, include/bib/psu-repro.bib]
    csl: include/bib/apa.csl

editor: source
    