---
title: "schedule"
---

## August 21-25 {- #week-01}

### Monday, August 21 {-}

**Introduction to the course: Why trust science?**

- Read
  - (Recommended) [@Oreskes2017, Chapter 1, pp. 55-68] | [PDF on Canvas](https://psu.instructure.com/courses/2280122/files/folder/readings?preview=152167033).
- [Class notes](notes/wk01-2023-08-21.qmd)

### Wednesday, August 23 {-}

**Don't Fool Yourself**

- Read
    - [@Feynman1974-ld].
    - (Recommended) [@sagan-1996-baloney], Chapter 12, The Fine Art of Baloney Detection. [PDF on Canvas](https://psu.instructure.com/courses/2280122/files/folder/readings?preview=151876796)
- [Class notes](notes/wk01-2023-08-23.qmd)

### Friday, August 25 {-}

**How to read a scientific paper**

- Read
    - [@Carey2020-ut]
    - [@Ruben2016-om] (for fun)
- [Assignment]{.green_assigned}
    - [Exercise 01: Reading a scientific paper](exercises/ex01-read-a-scientific-paper.qmd)
- [Class notes](notes/wk01-2023-08-25.qmd)

---

## August 28-31 {- #week-02}

### Monday, August 28 {-}

**How science works (or should)**

- Read
    - [@Ritchie2020-fm], Chapter 1. [Alternate link to PDF on Canvas](https://psu.instructure.com/files/144654645/download?download_frd=1).
    - [@Nosek2012-al]. [Alternate link to PDF on Canvas](https://psu.instructure.com/files/144654434/download?download_frd=1)
- [Class notes](notes/wk02-2023-08-28.qmd)

### Wednesday, August 30 {-}

**Scientific norms and counter-norms**

- Read
    - [@Merton1973-vf]. [PDF on Canvas](https://psu.instructure.com/files/144517091/download?download_frd=1).
    - [@Mitroff1974-pp]. [PDF on Canvas](https://psu.instructure.com/courses/2280122/files/folder/readings?preview=151876801).
- [Assignment]{.green_assigned}
    - Complete (anonymous) [survey](https://forms.gle/reRw9sYUzsYHUsqz9) on scientific norms and counter-norms. **No write-up**.
- [Class notes](notes/wk02-2023-08-30.qmd)

### Friday, September 1 {-}

**Work session: Norms and counter-norms**

- Survey 02: [From raw data to results](surveys/survey-02.qmd)
- [Due]{.orange_due}
    - [Exercise 01: Reading a scientific paper](exercises/ex01-read-a-scientific-paper.qmd)
- [Assignment]{.green_assigned}
    - [Exercise 02: Norms and counter-norms write-up](exercises/ex02-norms-counternorms.qmd)
- [Class notes](notes/wk02-2023-09-01.qmd)

---

## September 4-8 {- #week-03}

### Monday, September 4

**Labor Day: NO CLASS**

### Wednesday, September 6 {-}

**Adherence to norms and counter-norms**

- Read
    - [@Kardash2012-kq](https://doi.org/10.1007/s11251-011-9195-0).
    - [@Macfarlane2008-tc](https://doi.org/10.1007/s10805-008-9055-y).
<!-- - Skim -->
<!--     - [@Anderson2010-rl](http://dx.doi.org/10.1353/jhe.0.0095). -->
<!--     - [@Kim2018-tr](https://doi.org/10.1177/0971721817744438). -->
- [Class notes](notes/wk03-2023-09-06.qmd)

### Friday, September 8 {-}

**A replication crisis (or not)**

- Read
    - [@Ritchie2020-fm], Chapter 2. [PDF on Canvas](https://psu.instructure.com/courses/2280122/files/folder/readings?preview=151876802).
    - [@Begley2012-cr].
- [Due]{.orange_due}
    - [Exercise 02: Norms and counter-norms write-up](exercises/ex02-norms-counternorms.qmd)
- [Class notes](notes/wk03-2023-09-08.qmd)

---

## September 11-15 {- #week-04}

### Monday, September 11 {-}

**Replication attempt: The "Lady Macbeth Effect"**

- Read
    - [@Zhong2006-nf].
    - [@Earp2014-ek].
- [Class notes](notes/wk04-2023-09-11.qmd)

### Wednesday, September 13 {-}

**Replication attempt: Priming effect**

- Read
    - [@Bargh1996-yv]; [PDF on Canvas](https://psu.instructure.com/courses/2280122/files/folder/readings?preview=151876806)
    - [@Doyen2012-ib]
- [Class notes](notes/wk04-2023-09-13.qmd)

### Friday, September 15 {-}

**Work session: Replication with R, R Markdown, & Quarto**

- Review
  - [Survey 01 report](surveys/survey-01.qmd)
  - [Survey 02 report](surveys/survey-02.qmd)
- [Class notes](notes/wk04-2023-09-15.qmd)

---

## September 18-22 {- #week-05}

### Monday, September 18 {-}

**Replication in cancer biology**

- Read
    - [@Errington2021-dp]
    - (skim) [@Errington2021-sy]
- [Class notes](notes/wk05-2023-09-18.qmd)

### Wednesday, September 20 {-}

**What R we talking about?**

- Read
    - [@Fidler2021-xn], especially sections 1, 2, and 3.1-3.2.
    - (Skim) [@Nosek2022-hv] or [@goodman_what_2016]
- [Class notes](notes/wk05-2023-09-20.qmd)

### Friday, September 22 {-}

- Catch-up

**Work session: Scientific integrity**

- [Assignment]{.green_assigned}
    - [Exercise 03: Violations of scientific integrity](exercises/ex03-scientific-integrity.qmd)

---

## September 25-29 {- #week-06}

### Monday, September 25

**NO CLASS**

### Wednesday, September 27 {-}

**Fraud & misconduct**

- Read
    - [@Ritchie2020-fm], Chapter 3
    - [@Bhattacharjee2013-rw], [PDF on Canvas](https://psu.instructure.com/courses/2280122/files/folder/readings?preview=154161167)
    - (Skim) [@Levelt2012-ap]
    - (Skim) [@Carpenter2012-qy]
- [Class notes](notes/wk06-2023-09-27.qmd)

### Friday, September 29 {-}

**P-hacking**

*On Zoom*: <https://psu.zoom.us/my/rogilmore>. Check-in for attendance. Join from anywhere convenient to you.

- [Due]{.orange_due}
    - [Exercise 03: Violations of scientific integrity](exercises/ex03-scientific-integrity.qmd)
- [Assignment]{.green_assigned}
    - [Exercise 04: P-hack your way to scientific glory](exercises/ex04-p-hacking.qmd) write-up.
- Work session
    - [Final project proposals](exercises/final-project.qmd), [due Friday, October 13]{.orange_due}.

---

## October 2-6 {- #week-07}

### Monday, October 2 {-}

**Retraction and scientific integrity**

- Read
    - [@Brainerd2018-iy]
- [Class notes](notes/wk07-2023-10-02.qmd)

### Wednesday, October 4 {-}

**Questionable research practices**

- Read
    - [@simmons_false-positive_2011]
- Watch
    - [@Ngiam2020-ln]()
- [Class notes](notes/wk07-2023-10-04.qmd)

### Friday, October 6 {-}

**More on questionable research practices**

- [Due]{.orange_due}
    - [Exercise 04: P-hack your way to scientific glory](exercises/ex04-p-hacking.qmd) write-up.
- [Class notes](notes/wk07-2023-10-06.qmd)
- Work session
    - [Final project proposals](exercises/final-project.qmd), [due Friday, October 13]{.orange_due}.

---
    
## October 9-13 {- #week-08}

### Monday, October 9 {-}

**Prevalence of QRPs**

- Read
    - [@John2012-tk]
- (Optional) Enter your [Exercise 04](exercises/ex04-p-hacking.qmd) data into [this](https://docs.google.com/spreadsheets/d/1JI_Qih4wCzUrYTQYE3dpvVx2C7GdzfUZq0a3QhqQyeE/edit?usp=sharing) anonymous spreadsheet.
- Discuss [Exercise 04: P-hack your way to scientific glory](exercises/ex04-p-hacking.qmd).
- [Class notes](notes/wk08-2023-10-09.qmd)

### Wednesday, October 11 {-}

**File drawer effect**

- [Assignment]{.green_assigned}
    - [Exercise 05: Alpha, Power, Effect Sizes, & Sample Size](exercises/ex05-apes.qmd)
- Read
    - [@Rosenthal1979-zi]
    - [@Franco2014-yu]
- [Class notes](notes/wk08-2023-10-11.qmd)

### Friday, October 13 {-}

**NO CLASS MEETING**

- [Due]{.orange_due}
    - [Final project](exercises/final-project.qmd) proposal

---

## October 16-20 {- #week-09}

### Monday, October 16 {-}

**Negligence**

- Read
    - [@Ritchie2020-fm], Chapter 5
    - [@Nuijten2015-ul]
    - [@Szucs2017-fc]
- [Class notes](notes/wk09-2023-10-16.qmd)

### Wednesday, October 18 {-}

**Hype**

- Read
    - [@Ritchie2020-fm], Chapter 6
    - [@Carney2010-gq]
    - (Optional) [@Ranehill2015-dj]()
- Watch
    - [@Cuddy2012-zx](https://www.ted.com/talks/amy_cuddy_your_body_language_may_shape_who_you_are)
- [Class notes](notes/wk09-2023-10-18.qmd)
 
### Friday, October 20 {-}

**Work session on replication**

- [Discuss draft]{.orange_due}
    - [Exercise 05: Alpha, Power, Effect Sizes, & Sample Size]() write-up
- [Assignment]{.green_assigned}
    - [Exercise 06: Replication](exercises/ex06-replication.qmd)

---

## October 23-27 {- #week-10}

### Monday, October 23 {-}

**Solutions**

- [Final due]{.orange_due}
    - [Exercise 05: Alpha, Power, Effect Sizes, & Sample Size]() write-up
- Read
    - [@munafo_manifesto_2017]
    - [@Begley2013-vm]
- [Class notes](notes/wk10-2023-10-23.qmd)

### Wednesday, October 25 {-}

**Changing journal policies**

- Read
    - [@nosek_promoting_2015]
    - [@Gilmore2020-sl]
    - [@Srcd2019-hg]
- [Class notes](notes/wk10-2023-10-25.qmd)

### Friday, October 27 {-}

**Final project work day**

- [Due]{.orange_due}
    - [Exercise 06: Replication](exercises/ex06-replication.qmd)
- [Optional Extra Credit Assignment]{.green_assigned}
      - For 5 extra credit points, write a paragraph that summarizes the main findings of [@Camerer2018-tr]. [Due Friday, November 3]{.due_orange}.

---

## October 30 - November 3 {- #week-11}

### Monday, October 30 {-}

**Large-scale replication studies**

- Read
    - [@collaboration_estimating_2015]
- [Class notes](notes/wk11-2023-10-30.qmd)

### Wednesday, November 1 {-}

**Meta-analysis & many analysts**

- Read
    - [@Wilson2014-ol]
    - [@Silberzahn2018-st]
- [Class notes](notes/wk11-2023-11-01.qmd)

### Friday, November 3 {-}

**Final project work day**

- [Optional Extra Credit Assignment]{.orange_due}
    - For 5 extra credit points, write a paragraph that summarizes the main findings of [@Camerer2018-tr].
      
---

## November 6-10 {- #week-12}

### Monday, November 6 {-}

**Preregistration**

- Read
    - [@Nosek2018-jk]
    - [@Ledgerwood2018-sn] or [@Goldin-Meadow2016-mc]
    - (Optional) [@Claesen2021-ae]
- Explore
    - [clinicaltrials.gov](https://clinicaltrials.gov/)
- [Class notes](notes/wk12-2023-11-06.qmd)

### Wednesday, November 8 {-}

**Data sharing**

- Read
    - [@Houtkoop2018-tl]
    - [@Tenopir2020-mq]
    - (Optional) [@GilmoreAdolph2017]
    - (Optional) [@Meyer2018-vk]
    - (Optional) [@National_Institutes_of_Health_undated-it](https://grants.nih.gov/grants/guide/notice-files/NOT-OD-21-013.html)
- [Class notes](notes/wk12-2023-11-08.qmd)

### Friday, November 10 {-}

**Work session: Data sharing**

- [Assignment distributed]{.green_assigned}
    - [Exercise 07: Data and materials sharing](exercises/ex07-sharing.qmd)
- [Final project survey]{.green_assigned}
    - Please complete the [final project survey](https://forms.gle/L92wWFSpcdyLT4MR9).

---

## November 13-17 {- #week-13}

### Monday, November 13 {-}

**Materials, code, & protocol sharing**

- Read
    - [@Soska2021-mh]
    - [@Gilroy2019-bf]
- Explore
    - [protocols.io](https://www.protocols.io/)
    - [Journal of Visualized Experiments (JOVE)](https://www.jove.com/)
- [Class notes](notes/wk13-2023-11-13.qmd)

### Wednesday, November 15 {-}

**Open science tools**

- Read
    - [@Kathawalla2021-tk]
    - [@Cruwell2019-nz]
- Explore
    - [@FORRT_undated-pl]
- [Class notes](notes/wk13-2023-11-15.qmd)

### Friday, November 17 {-}

**Final project work day**

- [Assignment Due]{.orange_due}
    - [Exercise 07: Data and materials sharing](exercises/ex07-sharing.qmd)

---

## November 20-24 **Thanksgiving Break**

---

## November 27 - December 1 {- #week-14}

### Monday, November 27 {-}

**In-class final project work day**

### Wednesday, November 29 {-}

**In-class final project work day**

### Friday, December 1 {-}

**Project presentations**

- [Schedule]()

---

## December 4-8 {- #week-15}

### Monday, December 4 {-}

**Project presentations**

- [Schedule]()

### Wednesday, December 6 {-}

**Project presentations**

- [Schedule]()

### Friday, December 8 {-}

- Class wrap-up

---
    
## December 11-15 {- #finals-week}

### Wednesday, December 13 {-}

- [Due]{.orange_due}
  - [Final project](exercises/final-project.qmd) write-ups due 5:00 PM.
  
